version: '2'

#networks:
#  1panel-network:
#    external: true

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn innrg.wsgi:application -c /app/gunicorn.conf.py
    volumes:
      - .:/app
      - /root/innrg/static_volume:/app/static
      - /root/innrg/logs/gunicorn:/var/log/gunicorn
    ports:
      - "8080:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
#    networks:
#      - 1panel-network
#    restart: always
#    deploy:
#      resources:
#        limits:
#          cpus: '1.5'
#          memory: 2G