# Generated by Django 5.2.3 on 2025-06-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0004_remove_product_customer_product_city_product_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='factory_remark',
            field=models.TextField(blank=True, null=True, verbose_name='厂家备注'),
        ),
    ]
