# Generated by Django 5.2.3 on 2025-06-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0005_product_factory_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qrcode_id',
            field=models.CharField(db_index=True, max_length=16, unique=True, verbose_name='二维码ID'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='warranty_period',
            field=models.IntegerField(default=1095, verbose_name='保修期(天)'),
        ),
    ]
