# Generated by Django 5.2.3 on 2025-07-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0006_alter_product_qrcode_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationrecord',
            name='operator',
            field=models.CharField(max_length=50, verbose_name='操作人'),
        ),
    ]
