# Generated by Django 5.2.3 on 2025-07-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0007_alter_operationrecord_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='访问码')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否有效')),
                ('validity_period', models.IntegerField(default=-1, verbose_name='有效期(天)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '访问码',
                'verbose_name_plural': '访问码',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='installer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='安装人员信息'),
        ),
    ]
