# Generated by Django 5.2.3 on 2025-07-18 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('productApp', '0008_accesscode_product_installer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='附件名称')),
                ('file_url', models.URLField(max_length=500, verbose_name='文件URL')),
                ('file_type', models.IntegerField(choices=[(1, '图片'), (2, '文档'), (3, '视频'), (4, '其他')], default=4, verbose_name='文件类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('object_id', models.PositiveIntegerField(verbose_name='关联对象ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='关联模型')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='productApp__content_17050c_idx')],
            },
        ),
    ]
