# Generated by Django 5.2.3 on 2025-07-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0010_remove_repairrecord_customer_repairrecord_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='文件名'),
        ),
    ]
